/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RetailerId = IDL.Nat;
export const ProductId = IDL.Nat;
export const ListingId = IDL.Nat;
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'discontinued' : IDL.Null,
  'outOfStock' : IDL.Null,
});
export const Time = IDL.Int;
export const PromoDetails = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'price' : IDL.Nat,
  'startDate' : Time,
});
export const NewListing = IDL.Record({
  'id' : ListingId,
  'status' : ListingStatus,
  'createdAt' : Time,
  'productId' : ProductId,
  'updatedAt' : Time,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
  'promo' : IDL.Opt(PromoDetails),
  'retailerId' : RetailerId,
});
export const CartItem = IDL.Record({
  'listingId' : ListingId,
  'quantity' : IDL.Nat,
});
export const DeliveryMethod = IDL.Variant({
  'home' : IDL.Record({ 'address' : IDL.Text }),
  'pickupPoint' : IDL.Record({ 'pointId' : IDL.Nat }),
});
export const PaymentMethod = IDL.Variant({
  'icp' : IDL.Null,
  'zar' : IDL.Null,
  'nomayini' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'inDelivery' : IDL.Record({ 'driverId' : IDL.Principal }),
  'assigned' : IDL.Record({ 'shopperId' : IDL.Principal }),
  'cancelled' : IDL.Text,
  'pending' : IDL.Null,
  'purchased' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'deliveryMethod' : DeliveryMethod,
  'updatedAt' : Time,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PersonalShopperStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const PersonalShopperApplication = IDL.Record({
  'status' : PersonalShopperStatus,
  'applicant' : IDL.Principal,
  'name' : IDL.Text,
  'selfieImage' : ExternalBlob,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'submittedAt' : Time,
  'reviewedAt' : IDL.Opt(Time),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PickupPointApplication = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  }),
  'applicant' : IDL.Principal,
  'province' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'townSuburb' : IDL.Text,
  'kycDocs' : IDL.Vec(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'imageRefs' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'preferredImage' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
});
export const HolidayOverride = IDL.Record({
  'closeTime' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'name' : IDL.Text,
  'isOpen' : IDL.Bool,
  'openTime' : IDL.Opt(IDL.Nat),
});
export const WeekdayTimeRange = IDL.Record({
  'day' : IDL.Nat,
  'closeTime' : IDL.Nat,
  'openTime' : IDL.Nat,
});
export const OpeningHours = IDL.Record({
  'holidayOverrides' : IDL.Vec(HolidayOverride),
  'weeklySchedule' : IDL.Vec(WeekdayTimeRange),
});
export const RetailerInput = IDL.Record({
  'province' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : OpeningHours,
  'phone' : IDL.Text,
  'townSuburb' : IDL.Text,
});
export const Retailer = IDL.Record({
  'id' : RetailerId,
  'province' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'openingHours' : OpeningHours,
  'phone' : IDL.Text,
  'townSuburb' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ShopListing = IDL.Record({
  'activePrice' : IDL.Nat,
  'isPromoActive' : IDL.Bool,
  'listingId' : ListingId,
  'normalPrice' : IDL.Nat,
  'retailerName' : IDL.Text,
  'stock' : IDL.Nat,
  'savings' : IDL.Opt(IDL.Nat),
  'retailerId' : RetailerId,
});
export const ShopProduct = IDL.Record({
  'id' : ProductId,
  'listings' : IDL.Vec(ShopListing),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePersonalShopper' : IDL.Func([IDL.Principal], [], []),
  'approvePickupPoint' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'associateRetailerPrincipal' : IDL.Func([IDL.Principal, RetailerId], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createListing' : IDL.Func(
      [RetailerId, ProductId, IDL.Nat, IDL.Nat],
      [NewListing],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(CartItem), DeliveryMethod, PaymentMethod],
      [OrderRecord],
      [],
    ),
  'createPersonalShopperApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [PersonalShopperApplication],
      [],
    ),
  'createPickupPointApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
      ],
      [PickupPointApplication],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [Product],
      [],
    ),
  'createRetailer' : IDL.Func([RetailerInput], [Retailer], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'deleteRetailer' : IDL.Func([RetailerId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogue' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(NewListing)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getMyRetailer' : IDL.Func([], [IDL.Opt(Retailer)], ['query']),
  'getMyRetailerInventory' : IDL.Func([], [IDL.Vec(NewListing)], ['query']),
  'getMyRetailerOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderRecord)], ['query']),
  'getPersonalShopperApplication' : IDL.Func(
      [],
      [IDL.Opt(PersonalShopperApplication)],
      ['query'],
    ),
  'getPersonalShopperStatus' : IDL.Func(
      [],
      [IDL.Opt(PersonalShopperStatus)],
      ['query'],
    ),
  'getPickupPointApplication' : IDL.Func(
      [],
      [IDL.Opt(PickupPointApplication)],
      ['query'],
    ),
  'getPickupPointStatus' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getRetailer' : IDL.Func([RetailerId], [IDL.Opt(Retailer)], ['query']),
  'getRetailerListings' : IDL.Func(
      [RetailerId],
      [IDL.Vec(NewListing)],
      ['query'],
    ),
  'getRetailerPrincipalMapping' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(RetailerId)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllListings' : IDL.Func([], [IDL.Vec(NewListing)], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listPendingPersonalShopperApplications' : IDL.Func(
      [],
      [IDL.Vec(PersonalShopperApplication)],
      ['query'],
    ),
  'listPendingPickupPointApplications' : IDL.Func(
      [],
      [IDL.Vec(PickupPointApplication)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listRetailers' : IDL.Func([], [IDL.Vec(Retailer)], ['query']),
  'rejectPersonalShopper' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'rejectPickupPoint' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'removePromo' : IDL.Func([ListingId], [NewListing], []),
  'removeRetailerPrincipal' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setPromo' : IDL.Func(
      [ListingId, IDL.Nat, Time, IDL.Opt(Time)],
      [NewListing],
      [],
    ),
  'updateListing' : IDL.Func(
      [ListingId, IDL.Nat, IDL.Nat, ListingStatus],
      [NewListing],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [OrderRecord], []),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'updateRetailer' : IDL.Func([RetailerId, RetailerInput], [Retailer], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RetailerId = IDL.Nat;
  const ProductId = IDL.Nat;
  const ListingId = IDL.Nat;
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'discontinued' : IDL.Null,
    'outOfStock' : IDL.Null,
  });
  const Time = IDL.Int;
  const PromoDetails = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'price' : IDL.Nat,
    'startDate' : Time,
  });
  const NewListing = IDL.Record({
    'id' : ListingId,
    'status' : ListingStatus,
    'createdAt' : Time,
    'productId' : ProductId,
    'updatedAt' : Time,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
    'promo' : IDL.Opt(PromoDetails),
    'retailerId' : RetailerId,
  });
  const CartItem = IDL.Record({
    'listingId' : ListingId,
    'quantity' : IDL.Nat,
  });
  const DeliveryMethod = IDL.Variant({
    'home' : IDL.Record({ 'address' : IDL.Text }),
    'pickupPoint' : IDL.Record({ 'pointId' : IDL.Nat }),
  });
  const PaymentMethod = IDL.Variant({
    'icp' : IDL.Null,
    'zar' : IDL.Null,
    'nomayini' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'inDelivery' : IDL.Record({ 'driverId' : IDL.Principal }),
    'assigned' : IDL.Record({ 'shopperId' : IDL.Principal }),
    'cancelled' : IDL.Text,
    'pending' : IDL.Null,
    'purchased' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'deliveryMethod' : DeliveryMethod,
    'updatedAt' : Time,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PersonalShopperStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const PersonalShopperApplication = IDL.Record({
    'status' : PersonalShopperStatus,
    'applicant' : IDL.Principal,
    'name' : IDL.Text,
    'selfieImage' : ExternalBlob,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'submittedAt' : Time,
    'reviewedAt' : IDL.Opt(Time),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PickupPointApplication = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Text,
    }),
    'applicant' : IDL.Principal,
    'province' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'townSuburb' : IDL.Text,
    'kycDocs' : IDL.Vec(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'imageRefs' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'preferredImage' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
  });
  const HolidayOverride = IDL.Record({
    'closeTime' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'name' : IDL.Text,
    'isOpen' : IDL.Bool,
    'openTime' : IDL.Opt(IDL.Nat),
  });
  const WeekdayTimeRange = IDL.Record({
    'day' : IDL.Nat,
    'closeTime' : IDL.Nat,
    'openTime' : IDL.Nat,
  });
  const OpeningHours = IDL.Record({
    'holidayOverrides' : IDL.Vec(HolidayOverride),
    'weeklySchedule' : IDL.Vec(WeekdayTimeRange),
  });
  const RetailerInput = IDL.Record({
    'province' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : OpeningHours,
    'phone' : IDL.Text,
    'townSuburb' : IDL.Text,
  });
  const Retailer = IDL.Record({
    'id' : RetailerId,
    'province' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'openingHours' : OpeningHours,
    'phone' : IDL.Text,
    'townSuburb' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ShopListing = IDL.Record({
    'activePrice' : IDL.Nat,
    'isPromoActive' : IDL.Bool,
    'listingId' : ListingId,
    'normalPrice' : IDL.Nat,
    'retailerName' : IDL.Text,
    'stock' : IDL.Nat,
    'savings' : IDL.Opt(IDL.Nat),
    'retailerId' : RetailerId,
  });
  const ShopProduct = IDL.Record({
    'id' : ProductId,
    'listings' : IDL.Vec(ShopListing),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePersonalShopper' : IDL.Func([IDL.Principal], [], []),
    'approvePickupPoint' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'associateRetailerPrincipal' : IDL.Func(
        [IDL.Principal, RetailerId],
        [],
        [],
      ),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createListing' : IDL.Func(
        [RetailerId, ProductId, IDL.Nat, IDL.Nat],
        [NewListing],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(CartItem), DeliveryMethod, PaymentMethod],
        [OrderRecord],
        [],
      ),
    'createPersonalShopperApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [PersonalShopperApplication],
        [],
      ),
    'createPickupPointApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
        ],
        [PickupPointApplication],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [Product],
        [],
      ),
    'createRetailer' : IDL.Func([RetailerInput], [Retailer], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'deleteRetailer' : IDL.Func([RetailerId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogue' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(NewListing)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getMyRetailer' : IDL.Func([], [IDL.Opt(Retailer)], ['query']),
    'getMyRetailerInventory' : IDL.Func([], [IDL.Vec(NewListing)], ['query']),
    'getMyRetailerOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderRecord)], ['query']),
    'getPersonalShopperApplication' : IDL.Func(
        [],
        [IDL.Opt(PersonalShopperApplication)],
        ['query'],
      ),
    'getPersonalShopperStatus' : IDL.Func(
        [],
        [IDL.Opt(PersonalShopperStatus)],
        ['query'],
      ),
    'getPickupPointApplication' : IDL.Func(
        [],
        [IDL.Opt(PickupPointApplication)],
        ['query'],
      ),
    'getPickupPointStatus' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Variant({
              'pending' : IDL.Null,
              'approved' : IDL.Null,
              'rejected' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getRetailer' : IDL.Func([RetailerId], [IDL.Opt(Retailer)], ['query']),
    'getRetailerListings' : IDL.Func(
        [RetailerId],
        [IDL.Vec(NewListing)],
        ['query'],
      ),
    'getRetailerPrincipalMapping' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(RetailerId)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllListings' : IDL.Func([], [IDL.Vec(NewListing)], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listPendingPersonalShopperApplications' : IDL.Func(
        [],
        [IDL.Vec(PersonalShopperApplication)],
        ['query'],
      ),
    'listPendingPickupPointApplications' : IDL.Func(
        [],
        [IDL.Vec(PickupPointApplication)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listRetailers' : IDL.Func([], [IDL.Vec(Retailer)], ['query']),
    'rejectPersonalShopper' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'rejectPickupPoint' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'removePromo' : IDL.Func([ListingId], [NewListing], []),
    'removeRetailerPrincipal' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setPromo' : IDL.Func(
        [ListingId, IDL.Nat, Time, IDL.Opt(Time)],
        [NewListing],
        [],
      ),
    'updateListing' : IDL.Func(
        [ListingId, IDL.Nat, IDL.Nat, ListingStatus],
        [NewListing],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [OrderRecord], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'updateRetailer' : IDL.Func([RetailerId, RetailerInput], [Retailer], []),
  });
};

export const init = ({ IDL }) => { return []; };