/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CartItem { 'listingId' : ListingId, 'quantity' : bigint }
export type DeliveryMethod = { 'home' : { 'address' : string } } |
  { 'pickupPoint' : { 'pointId' : bigint } };
export interface DriverApplication {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : string },
  'applicant' : Principal,
  'vehicleDetails' : string,
  'name' : string,
  'submittedAt' : Time,
  'reviewedBy' : [] | [Principal],
  'email' : string,
  'phone' : string,
  'kycDocs' : Array<ExternalBlob>,
}
export interface ExpandedOrderItem {
  'listing' : [] | [NewListing],
  'retailer' : [] | [Retailer],
  'cartItem' : CartItem,
  'product' : [] | [Product],
}
export type ExternalBlob = Uint8Array;
export interface HolidayOverride {
  'closeTime' : [] | [bigint],
  'date' : Time,
  'name' : string,
  'isOpen' : boolean,
  'openTime' : [] | [bigint],
}
export type ListingId = bigint;
export type ListingStatus = { 'active' : null } |
  { 'discontinued' : null } |
  { 'outOfStock' : null };
export interface NewListing {
  'id' : ListingId,
  'status' : ListingStatus,
  'createdAt' : Time,
  'productId' : ProductId,
  'updatedAt' : Time,
  'stock' : bigint,
  'price' : bigint,
  'promo' : [] | [PromoDetails],
  'retailerId' : RetailerId,
}
export interface OpeningHours {
  'holidayOverrides' : Array<HolidayOverride>,
  'weeklySchedule' : Array<WeekdayTimeRange>,
}
export type OrderId = bigint;
export interface OrderRecord {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customer' : Principal,
  'createdAt' : Time,
  'deliveryMethod' : DeliveryMethod,
  'updatedAt' : Time,
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'inDelivery' : { 'driverId' : Principal } } |
  { 'assigned' : { 'shopperId' : Principal } } |
  { 'cancelled' : string } |
  { 'pending' : null } |
  { 'purchased' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type PaymentMethod = { 'icp' : null } |
  { 'zar' : null } |
  { 'nomayini' : null };
export interface PersonalShopperApplication {
  'status' : PersonalShopperStatus,
  'applicant' : Principal,
  'name' : string,
  'selfieImage' : ExternalBlob,
  'rejectionReason' : [] | [string],
  'submittedAt' : Time,
  'reviewedAt' : [] | [Time],
  'reviewedBy' : [] | [Principal],
  'email' : string,
  'phone' : string,
}
export type PersonalShopperStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export interface PickupPointApplication {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : string },
  'applicant' : Principal,
  'name' : string,
  'submittedAt' : Time,
  'reviewedBy' : [] | [Principal],
  'address' : string,
  'businessImage' : ExternalBlob,
  'contactNumber' : string,
}
export interface Product {
  'id' : ProductId,
  'imageRefs' : Array<ExternalBlob>,
  'name' : string,
  'description' : string,
  'preferredImage' : [] | [ExternalBlob],
  'category' : string,
}
export type ProductId = bigint;
export interface PromoDetails {
  'endDate' : [] | [Time],
  'price' : bigint,
  'startDate' : Time,
}
export interface Retailer {
  'id' : RetailerId,
  'province' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'address' : string,
  'openingHours' : OpeningHours,
  'phone' : string,
  'townSuburb' : string,
}
export type RetailerId = bigint;
export interface RetailerInput {
  'province' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'openingHours' : OpeningHours,
  'phone' : string,
  'townSuburb' : string,
}
export interface ShopListing {
  'activePrice' : bigint,
  'isPromoActive' : boolean,
  'listingId' : ListingId,
  'normalPrice' : bigint,
  'retailerName' : string,
  'stock' : bigint,
  'savings' : [] | [bigint],
  'retailerId' : RetailerId,
}
export interface ShopProduct {
  'id' : ProductId,
  'listings' : Array<ShopListing>,
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface ShopperOrderView {
  'order' : OrderRecord,
  'expandedItems' : Array<ExpandedOrderItem>,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeekdayTimeRange {
  'day' : bigint,
  'closeTime' : bigint,
  'openTime' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptShopperOrder' : ActorMethod<[OrderId], undefined>,
  'approveDriver' : ActorMethod<[Principal], undefined>,
  'approvePersonalShopper' : ActorMethod<[Principal], undefined>,
  'approvePickupPoint' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateRetailerPrincipal' : ActorMethod<
    [Principal, RetailerId],
    undefined
  >,
  'completeShopperOrder' : ActorMethod<[OrderId], OrderRecord>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createDriverApplication' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>],
    DriverApplication
  >,
  'createListing' : ActorMethod<
    [RetailerId, ProductId, bigint, bigint],
    NewListing
  >,
  'createOrder' : ActorMethod<
    [Array<CartItem>, DeliveryMethod, PaymentMethod],
    OrderRecord
  >,
  'createPersonalShopperApplication' : ActorMethod<
    [string, string, string, ExternalBlob],
    PersonalShopperApplication
  >,
  'createPickupPointApplication' : ActorMethod<
    [string, string, string, ExternalBlob],
    PickupPointApplication
  >,
  'createProduct' : ActorMethod<
    [string, string, ExternalBlob, string],
    Product
  >,
  'createRetailer' : ActorMethod<[RetailerInput], Retailer>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'deleteRetailer' : ActorMethod<[RetailerId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCatalogue' : ActorMethod<[], Array<ShopProduct>>,
  'getDriverApplication' : ActorMethod<[], [] | [DriverApplication]>,
  'getListing' : ActorMethod<[ListingId], [] | [NewListing]>,
  'getMyOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getMyRetailer' : ActorMethod<[], [] | [Retailer]>,
  'getMyRetailerInventory' : ActorMethod<[], Array<NewListing>>,
  'getMyRetailerOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderRecord]>,
  'getPersonalShopperApplication' : ActorMethod<
    [],
    [] | [PersonalShopperApplication]
  >,
  'getPersonalShopperStatus' : ActorMethod<[], [] | [PersonalShopperStatus]>,
  'getPickupPointApplication' : ActorMethod<[], [] | [PickupPointApplication]>,
  'getPickupPointStatus' : ActorMethod<
    [],
    [] | [
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : string }
    ]
  >,
  'getRetailer' : ActorMethod<[RetailerId], [] | [Retailer]>,
  'getRetailerListings' : ActorMethod<[RetailerId], Array<NewListing>>,
  'getRetailerPrincipalMapping' : ActorMethod<[Principal], [] | [RetailerId]>,
  'getShopperOrderDetails' : ActorMethod<[OrderId], [] | [ShopperOrderView]>,
  'getShopperOrderExpanded' : ActorMethod<[OrderId], [] | [ShopperOrderView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAllListings' : ActorMethod<[], Array<NewListing>>,
  'listAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listCategories' : ActorMethod<[], Array<string>>,
  'listEligibleDriverOrders' : ActorMethod<[], Array<OrderRecord>>,
  'listMyAssignedShopperOrders' : ActorMethod<[], Array<OrderRecord>>,
  'listPendingDriverApplications' : ActorMethod<[], Array<DriverApplication>>,
  'listPendingPersonalShopperApplications' : ActorMethod<
    [],
    Array<PersonalShopperApplication>
  >,
  'listPendingPickupPointApplications' : ActorMethod<
    [],
    Array<PickupPointApplication>
  >,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listRetailers' : ActorMethod<[], Array<Retailer>>,
  'listShopperEligiblePickupOrders' : ActorMethod<[], Array<OrderRecord>>,
  'rejectDriver' : ActorMethod<[Principal, string], undefined>,
  'rejectPersonalShopper' : ActorMethod<[Principal, string], undefined>,
  'rejectPickupPoint' : ActorMethod<[Principal, string], undefined>,
  'removePromo' : ActorMethod<[ListingId], NewListing>,
  'removeRetailerPrincipal' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPromo' : ActorMethod<[ListingId, bigint, Time, [] | [Time]], NewListing>,
  'updateListing' : ActorMethod<
    [ListingId, bigint, bigint, ListingStatus],
    NewListing
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], OrderRecord>,
  'updateProduct' : ActorMethod<[ProductId, string, string, string], Product>,
  'updateRetailer' : ActorMethod<[RetailerId, RetailerInput], Retailer>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];