/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageRef' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductRequest = IDL.Record({
  'id' : IDL.Nat,
  'province' : IDL.Text,
  'productName' : IDL.Text,
  'retailerName' : IDL.Text,
  'townSuburb' : IDL.Text,
});
export const Province = IDL.Record({
  'towns' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const Retailer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'products' : IDL.Vec(Product),
  'townSuburb' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addProvince' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addRetailer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getProductCatalog' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getProductRequests' : IDL.Func([], [IDL.Vec(ProductRequest)], ['query']),
  'getProvinces' : IDL.Func([], [IDL.Vec(Province)], ['query']),
  'getRetailersByTownSuburb' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Retailer)],
      ['query'],
    ),
  'requestNewProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageRef' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductRequest = IDL.Record({
    'id' : IDL.Nat,
    'province' : IDL.Text,
    'productName' : IDL.Text,
    'retailerName' : IDL.Text,
    'townSuburb' : IDL.Text,
  });
  const Province = IDL.Record({
    'towns' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const Retailer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'products' : IDL.Vec(Product),
    'townSuburb' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addProvince' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addRetailer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getProductCatalog' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getProductRequests' : IDL.Func([], [IDL.Vec(ProductRequest)], ['query']),
    'getProvinces' : IDL.Func([], [IDL.Vec(Province)], ['query']),
    'getRetailersByTownSuburb' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Retailer)],
        ['query'],
      ),
    'requestNewProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };