/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageRef' : string,
  'category' : string,
  'price' : bigint,
}
export interface ProductRequest {
  'id' : bigint,
  'province' : string,
  'productName' : string,
  'retailerName' : string,
  'townSuburb' : string,
}
export interface Province { 'towns' : Array<string>, 'name' : string }
export interface Retailer {
  'id' : bigint,
  'name' : string,
  'products' : Array<Product>,
  'townSuburb' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    bigint
  >,
  'addProvince' : ActorMethod<[string, Array<string>], undefined>,
  'addRetailer' : ActorMethod<[string, string], bigint>,
  'getProductCatalog' : ActorMethod<[bigint], Array<Product>>,
  'getProductRequests' : ActorMethod<[], Array<ProductRequest>>,
  'getProvinces' : ActorMethod<[], Array<Province>>,
  'getRetailersByTownSuburb' : ActorMethod<[string], Array<Retailer>>,
  'requestNewProduct' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];